### ISSUE TITLE
Follow-ups count is squared

### ISSUE THREAD

**Issue by nchouard** [penny-university/penny_university#285]
# Description
When `?upcoming_or_popular=true` is added to the `/chats` endpoint, the count is squared! Looks like we are super popular... but isn't right 😛 

## Details
This is how it looks on prod:
<img width="1475" alt="follow-ups squared" src="https://user-images.githubusercontent.com/31971995/86861164-092b2b80-c08c-11ea-93ff-64e450958169.png">

### Steps to reproduce
1. If it doesn't already exist, create a Penny Chat with at least 2 follow-ups
2. Make a GET request to `/api/chats?upcoming_or_popular=true`, and check the followUpCount

### Requirements
- [x] Follow up count from Penny Chat list should be correct
- [ ] Add a test to make sure follow up count is correct

**Comment by JnBrymn** [comment]
Weird... why am I seeing this: 
![image](https://user-images.githubusercontent.com/566533/86862041-092c2b00-c08e-11ea-9551-ed83a639f3fd.png)

**Comment by adamtaylor13** [comment]
So I've narrowed it down to this.

![image](https://user-images.githubusercontent.com/2922753/86985258-77d4bb80-c156-11ea-835e-8371d7dc6e7f.png)

The `follow_up_counts` field is definitely getting multiplied by itself somewhere, _I assume_ in the filter_queryset method. 

Here's why my hunch is the way it is:
![image](https://user-images.githubusercontent.com/2922753/86985387-bec2b100-c156-11ea-93ae-4ac7ce74f67b.png)

![image](https://user-images.githubusercontent.com/2922753/86985393-c4b89200-c156-11ea-94ca-2976f8c05bb2.png)

I believe [this note](https://docs.djangoproject.com/en/3.0/topics/db/aggregation/) explains why:

> Unlike aggregate(), annotate() is not a terminal clause. The output of the annotate() clause is a QuerySet; this QuerySet can be modified using any other QuerySet operation, including filter(), order_by(), or even additional calls to annotate().

However, I'll be honest, since I'm not a python guy I'm really unsure what's happening here. Things like the `filterset_class` are seemingly declared, but never used anywhere? I'm going to assume it's some django thing. But either way, perhaps the solution is to avoid "calling" this query set twice—first in `self.get_queryset()` and then again in `self.filter_queryset(queryset)`.

**Comment by deadbender** [comment]
Just tested, issue still exists. Setting up dev environment and checking what I can do here.

**Comment by deadbender** [comment]
Can't test at the moment but I think I've found a solution.

### How does this bug solve itself?

As seen above, on some systems the bug is able to solve itself. It appears that the way it is solving it is the following.

1. User opens https://pennyuniversity.com/chats and follow-ups shows a different value (squared)
2. User opens chat details, real number appears
3. /chats uses the new number rather than old until refresh.

That's how I've figured out how to fix it on my end.

### Solution

After a lot of searching I found that there are two different variables used for this. In /src/components/chats/ChatCard.tsx, it uses chat.followUpsCount, the variable providing that squared number. In ChatDetail.tsx, followUps.length is used which provides the correct number. It doesn't seem that chat.followUpsCount is used anywhere else other than this one line, so it should be okay to replace it with the correct value.

I will update when I have a dev environment setup and can test if this solution does work, if so I can throw it in a PR. Sorry for the lengthy issue reply, wanted to keep things as formal as they seem around here 😄

**Comment by nchouard** [comment]
Reopening to add tests around this bug.

**Comment by nchouard** [comment]
@deadbender Your initial thought wasn't a bad idea! The reason you were seeing that behavior is because only the `/api/chats?upcoming_or_popular=true` (the chats list endpoint) had the issue, and not `/api/chat/<id>` (the detail endpoint). When the user goes to the ChatDetail page, the correct `followUpCount` is retrieved from `/api/chat/<id>`, and updates the value in redux. When they go back to the list page, the updated value is still there in the store, and thus is correct.
