### ISSUE TITLE
Investigate extra calls to api/chats/ when loading the /chats/ and /profile/ page.

### ISSUE THREAD

**Issue by JnBrymn** [penny-university/penny_university#350]
If I visit the /chats/ page I see api requests for `api/chats?upcoming_or_popular=true` and  `api/chats?participants__user_id=3`. But I don't see any reason for the latter request.

Similarly when I visit /profile/3, I see an API request for `api/chats?upcoming_or_popular=true` and  `api/chats?participants__user_id=3` twice. In this case, it seems like only `api/chats?participants__user_id=3` should load and only once.

Let's make sure we're not hitting the database more than we have to.

**Comment by deadbender** [comment]
More elaboration on what I said in the chat initially:

I believe this is a side effect of the new private chats implementation. As far as I remember, I don't specifically call for `api/chats?participants__user_id`, but it's essentially what is called when `upcoming_or_popular` is called to make sure it shows private chats participated in by the user. My guess is that when upcoming_or_popular checks for it, the browser interprets that as two separate calls.

Not sure about the case of /profile though, that's very interesting that it calls upcoming_or_popular there as well...

**Comment by nchouard** [comment]
@deadbender That is actually not the case, because what is happening on the backend is not an API call, it is a database query, and the browser has no knowledge of it. What is more likely happening here is that with the way our pages are set up on the frontend, the fetch call for the main chat page and the fetch call for the profile page are being made on both pages. The `api/chats?upcoming_or_popular=true` is the call that fetches chats for the main chats list, while `api/chats?participants__user_id=3` is the call that fetches chats for the signed in user's profile.

**Comment by JnBrymn** [comment]
This issue is closely related to https://github.com/penny-university/penny_university/issues/362

**Comment by nchouard** [comment]
This was fixed by #379
