### ISSUE TITLE
/penny chat in a private channel works but sends failure message

### ISSUE THREAD

**Issue by JnBrymn** [penny-university/penny_university#370]
### Steps to Repro
In private channel type `/penny chat` and see:

![image](https://user-images.githubusercontent.com/566533/96506846-f1804900-121d-11eb-9956-0af59a093b7d.png)

but also see the modal pop up.

This might be confusing to users and lead them to mistrust the product is going to work.

**Comment by deadbender** [comment]
The only way I see around this is giving Penny "god access" to every channel in the organization, since I don't think you can customize when users can see Slack's errors (unless it only says it failed because Penny doesn't send back a response, but it should send back something I think :thinking:). But, as said before in the weekly call, I'm not sure many other Slack workspaces will enjoy a bot having that much access.

**Comment by nchouard** [comment]
This might not actually be a permissions issue. A few clues: https://stackoverflow.com/questions/63665120/slash-command-dispatch-failed

This is apparently a common issue https://github.com/slackapi/bolt-js/issues/579

**Comment by nchouard** [comment]
And this [Stack Overflow answer](https://stackoverflow.com/a/44960521) indicates that it will not send the correct channel if you make a command in a private channel. Maybe we are trying to use the channel id somewhere and it is failing.

**Comment by nchouard** [comment]
Hah! Found the issue and solved it by typing literally 2 characters 😂
